apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: MongoDB
  name: ocp-mongodb
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mongo:3.4.9
    importPolicy: {}
    name: "3.4.9"
  - annotations: null
    from:
      kind: ImageStreamTag
      name: "3.4.9"
    importPolicy: {}
    name: "3.4.x"
  - annotations: null
    from:
      kind: DockerImage
      name: mongo:latest
    importPolicy: {}
    name: latest

